Remove usage of .blank? and dependency on activesupport
chromebrew/chromebrew pull request #10355
Opened 2024-08-25 23:05 UTC by Zopolis4

## Description
yeah so we don't actually need to defensively program against our own code-- `gnome_packages` is initialized at line 2 of `lib/gnome.rb`, so it will never be nil, and we can just convert `@pkg_name` to a string so we don't have the `NoMethodError` problems.

also why do we have code for editing package files in `lib/downloader.rb`???

Tested & Working properly:
- [x] `x86_64`
- [ ] `i686`
- [ ] `armv7l`

### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/Zopolis4/chromebrew.git CREW_BRANCH=arid crew update \
&& yes | crew upgrade
```

2024-08-25 23:45 UTC, satmandu requested changes
Disagree on principle with avoiding active support's inclusion of .`blank?`. Blank is really useful and I'm sick of programming against failures of the core ruby developers to actually avoid situations where blank will work around ruby crapping out.

https://stackoverflow.com/a/20663389

![oXuhJ.png](https://github.com/user-attachments/assets/99eda915-e6db-47b6-9d90-699fcab02819)

2024-08-26 00:12 UTC, Zopolis4 commented
There are two usecases of it in our codebase-- one of which is entirely unnecessary as it is on a method that will never return nil, and another can be trivially replaced. Is it really that useful?

2024-08-26 00:14 UTC, satmandu commented
I have personally had it bite me multiple times on a bunch of stuff. Enough that I would have been using blank a lot more than I have been using it if we had it earlier.

Feel free to add the entire code block for it into one of the extra functions blocks if it makes you feel better, but I prefer to have another organization maintaining that code...

2024-08-26 00:17 UTC, satmandu commented
A function that routinely throws nomethod errors like `.empty?` does for stuff where it really shouldn't is IMHO broken.

2024-08-26 00:17 UTC, satmandu commented
<insert Joker meme...>

2024-08-26 00:19 UTC, Zopolis4 commented
fwiw, this is the [entire definition](https://justincypret.com/blog/activesupport-blank-vs-empty#blank-is-basically-an-alias-for-empty) of `.blank?`:
```ruby
# lib/active_support/core_ext/object/blank.rb
class Object
  def blank?
    respond_to?(:empty?) ? !!empty? : !self
  end
end
```

2024-08-26 00:20 UTC, Zopolis4 commented
but again-- there are two instances of it, one of which is unnecessary and one of which was trivial to replace.

2024-08-26 00:21 UTC, satmandu commented
> fwiw, this is the [entire definition](https://justincypret.com/blog/activesupport-blank-vs-empty#blank-is-basically-an-alias-for-empty) of `.blank?`:
> ```ruby
> # lib/active_support/core_ext/object/blank.rb
> class Object
>   def blank?
>     respond_to?(:empty?) ? !!empty? : !self
>   end
> end
> ```

Please add it to the functions block, because I don't ever want to get bitten by using `empty?` ever again.

2024-08-26 00:22 UTC, satmandu commented
> also why do we have code for editing package files in `lib/downloader.rb`???
> 
That's to automatically update hashes when building packages with version number updates. It's behind a force flag...

2024-08-26 00:23 UTC, Zopolis4 commented
> > fwiw, this is the [entire definition](https://justincypret.com/blog/activesupport-blank-vs-empty#blank-is-basically-an-alias-for-empty) of `.blank?`:
> > ```ruby
> > # lib/active_support/core_ext/object/blank.rb
> > class Object
> >   def blank?
> >     respond_to?(:empty?) ? !!empty? : !self
> >   end
> > end
> > ```
> 
> Please add it to the functions block, because I don't ever want to get bitten by using `empty?` ever again.

i'm happy to add it if or when we need it, but right now we don't need it.

2024-08-26 00:23 UTC, Zopolis4 commented
> > also why do we have code for editing package files in `lib/downloader.rb`???
> 
> That's to automatically update hashes when building packages with version number updates. It's behind a force flag...

ah. that probably makes more sense to have somewhere else, i'll take a look at it later

2024-08-26 00:24 UTC, satmandu commented
> > > fwiw, this is the [entire definition](https://justincypret.com/blog/activesupport-blank-vs-empty#blank-is-basically-an-alias-for-empty) of `.blank?`:
> > > ```ruby
> > > # lib/active_support/core_ext/object/blank.rb
> > > class Object
> > >   def blank?
> > >     respond_to?(:empty?) ? !!empty? : !self
> > >   end
> > > end
> > > ```
> > 
> > Please add it to the functions block, because I don't ever want to get bitten by using `empty?` ever again.
> 
> i'm happy to add it if or when we need it, but right now we don't need it.

Please do not remove the blank require without adding a function block for it.

I want it to be available.

2024-08-26 00:29 UTC, Zopolis4 commented
i do not see the logic in adding a method we do not use, but whatever

2024-08-26 00:36 UTC, satmandu commented
You're removing the usage of the `.blank?` method in favor of streamlining. My logic is that I am insisting on keeping the method around because I have every intention of continuing to use it, and furthermore I don't want people to avoid using it, because I think it is a safer method to use than `.empty?`

2024-08-26 00:37 UTC, uberhacker commented
Would it make sense to propose an upstream improvement to `empty` so it behaves like `blank`?  It's confusing to have multiple functions when the proper expected behavior of a single function would keep it simple.

2024-08-26 00:39 UTC, Zopolis4 commented
my logic is that there's no need to use a helper method if we don't need to use it, and that it makes sense to limit checks to what is relevant. 

if something will never be nil, it is misleading and unnecessary to check it with `.blank?` instead of `.empty?` or whatever is appropriate in this scenario. 

if a variable may be nil, there still tends to be a way to handle it using ruby's built in features. 

if there is a situation where `.blank?` is unequivocally required, then i see no problem in using it, but if it is not then there's no need.

2024-08-26 00:39 UTC, Zopolis4 commented
> Would it make sense to propose an upstream improvement to `empty` so it behaves like `blank`? It's confusing to have multiple functions when the proper expected behavior of a single function would keep it simple.

i'll have a look if anyone has asked, but I don't love our odds of changing the ruby upstream language if rails wasn't able to. still, always worth a shot!

2024-08-26 00:42 UTC, satmandu commented
> my logic is that there's no need to use a helper method if we don't need to use it, and that it makes sense to limit checks to what is relevant. 
> 
> if something will never be nil, it is misleading and unnecessary to check it with `.blank?` instead of `.empty?` or whatever is appropriate in this scenario. 
> 
> if a variable may be nil, there still tends to be a way to handle it using ruby's built in features. 
> 
> if there is a situation where `.blank?` is unequivocally required, then i see no problem in using it, but if it is not then there's no need.


Yes, but sometimes you end up with an unexpected `nil`.

Blank handles that. Handling unexpected cases is safer.

2024-08-26 00:46 UTC, satmandu commented
> > Would it make sense to propose an upstream improvement to `empty` so it behaves like `blank`? It's confusing to have multiple functions when the proper expected behavior of a single function would keep it simple.
> 
> i'll have a look if anyone has asked, but I don't love our odds of changing the ruby upstream language if rails wasn't able to. still, always worth a shot!

Agreed on the odds, which is why i didn't try to upstream it.

2024-08-26 00:49 UTC, Zopolis4 commented
agree to disagree on this one-- i prefer to avoid defensive programming whenever possible, and i'd rather know exactly where my codebase is interacting with external data and the source of unknowns, whereas it looks like you'd prefer to optimise for eliminating the possibility of these kinds of bugs, which is fair enough.

2024-08-26 02:02 UTC, Zopolis4 commented
also in terms of more practical concerns-- i can't add blank as a helper function without the stuff from #10343

2024-09-01 22:52 UTC, satmandu commented
> agree to disagree on this one-- i prefer to avoid defensive programming whenever possible, and i'd rather know exactly where my codebase is interacting with external data and the source of unknowns, whereas it looks like you'd prefer to optimise for eliminating the possibility of these kinds of bugs, which is fair enough.

This is my medical and public health and engineering training kicking in... Systemic fixes help prevent downstream issues.

2025-02-10 22:43 UTC, Zopolis4 commented
With the disagreements over the value of `.blank?`, and the significant increase in usage of external gems in the codebase anyways, this isn't a battle worth fighting.

2025-02-10 22:43 UTC, closed without merging