Remove need for essential_deps field in device.json
chromebrew/chromebrew pull request #10394
Opened 2024-09-01 22:45 UTC by Zopolis4

## Description
The definition of what is an 'essential' package has been confused. Essential packages are those that are absolutely required for chromebrew to run, and only chromebrew. If you remove lz4, zstd can no longer decompress `.tar.lz` binaries-- this is not required for ruby to run, and thus is not an essential package.

As such, the list of essential packages is actually quite short, and the only complexity required is in ensuring we have the right `glibc_lib_*` or `glibc_build_*` package.

##
Tested & Working properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l`
##
### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/Zopolis4/chromebrew.git CREW_BRANCH=ughhhh crew update \
&& yes | crew upgrade
```

2024-09-01 22:48 UTC, satmandu requested changes
I would define essential packages as those required to keep Chromebrew functions from breaking.

Being able to install packages requires zstd and its dependencies, so I don't understand why zstd isn't essential...

2024-09-01 22:49 UTC, satmandu commented
Also, we want to make sure zstd isn't removed, because otherwise we are going to get support issues with people who didn't realize they were breaking their systems.

2024-09-01 22:53 UTC, Zopolis4 commented
> Being able to install packages requires zstd and its dependencies, so I don't understand why zstd isn't essential

zstd is essential, which is why I've kept it as an essential package.

2024-09-01 22:55 UTC, Zopolis4 commented
![image](https://github.com/user-attachments/assets/0976f578-8244-4017-9ab0-b367a33a38d6)
as you can see, removing lz4 does not break the basic functionality of crew, hence why it is not an essential package.

2024-09-01 22:58 UTC, satmandu commented
```
chronos@cheekon-x86_64:2.27 M90 /usr/local/lib/crew/packages (master >|SPARSE)$ upx -d `which zstd`
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.4       Markus Oberhumer, Laszlo Molnar & John Reiser    May 9th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1102781 <-    382512   34.69%   linux/amd64   zstd

Unpacked 1 file.
chronos@cheekon-x86_64:2.27 M90 /usr/local/lib/crew/packages (master >|SPARSE)$ ../tools/getrealdeps.rb zstd
Checking for the runtime dependencies of zstd...

Package zstd has runtime library dependencies on these packages:
  depends_on 'gcc_lib' # R
  depends_on 'glibc' # R
  depends_on 'lz4' # R
  depends_on 'xzutils' # R
  depends_on 'zlib' # R
chronos@cheekon-x86_64:2.27 M90 /usr/local/lib/crew/packages (master >|SPARSE)$ lddtree `which zstd`
/usr/local/bin/zstd (interpreter => /lib64/ld-linux-x86-64.so.2)
    libz.so.1 => /usr/local/lib64/libz.so.1
    liblzma.so.5 => /usr/local/lib64/liblzma.so.5
    liblz4.so.1 => /usr/local/lib64/liblz4.so.1
    libpthread.so.0 => /usr/local/lib64/libpthread.so.0
    libc.so.6 => /usr/local/lib64/libc.so.6
    ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
chronos@cheekon-x86_64:2.27 M90 /usr/local/lib/crew/packages (master >|SPARSE)$
```

2024-09-01 22:59 UTC, satmandu commented
All dependencies of zstd need to be installed...

2024-09-01 23:00 UTC, satmandu commented
Otherwise installs break.

2024-09-01 23:03 UTC, Zopolis4 commented
> All dependencies of zstd need to be installed...

This is not the case. As I have shown, `lz4` can be removed and crew will still function.

2024-09-01 23:12 UTC, satmandu commented
> > All dependencies of zstd need to be installed...
> 
> This is not the case. As I have shown, `lz4` can be removed and crew will still function.

My experience is that installs break.

Please confirm that installs do not break with your changes by passing the REPO and BRANCH flags to the installer after deleting Chromebrew in a container.

We should really just have a unit test for this triggered with any changes in `install.sh` or to stuff like packages in `buildessential` and `core` when packages in those have their dependencies change, just to make sure installs don't break. Would that be overkill?

(Maybe a locally triggered unit test that doesn't burden GitHub's Action servers would make the most sense? Doing a test install takes about 15 min on my systems at most.)

2024-09-01 23:13 UTC, uberhacker commented
> > All dependencies of zstd need to be installed...
> 
> This is not the case. As I have shown, `lz4` can be removed and crew will still function.

Yes, but do fresh installs still work with it removed?  We cannot break fresh installs under any circumstances or we will antagonize new users and create a stampede of incoming issues.

2024-09-01 23:15 UTC, satmandu commented
(I'm not trying to be dogmatic for the sake of being dogmatic — just being overly protective because it is annoying to track down breakage after the fact. It would be nice to delegate that protectiveness to some automatic mechanism like we have done with our other unit tests, because refactoring can be really nice to streamline and cut out excess.)

2024-09-01 23:18 UTC, Zopolis4 commented
I have just tested a fresh install using this branch, everything works.

2024-09-01 23:50 UTC, satmandu commented
> I have just tested a fresh install using this branch, everything works. 

Just keep in mind that dependencies are lowest common denominator for all of our systems for the most part.

Do installs work on i686 + pre-M126/post-M126 systems on both x86_64 + Arm...

There is a reason that essential packages is currently set to expand to include all dependencies. 

If zstd doesn't have dependencies installed, it will try to use system libraries. If those aren't available... I think crew then tries to use the system zstd... That isn't available on the oldest systems.

2024-09-01 23:55 UTC, Zopolis4 commented
What i'm trying to convey here is that zstd doesn't need some dependencies in order to function for chromebrew's usage of it. zstd is able to decompress `.tar.zst` files and run ruby without `lz4` installed, so we don't need it for basic functionality.

2024-09-01 23:58 UTC, Zopolis4 commented
i.e. we aren't breaking zstd by removing lz4. we might be removing its ability to decompress `.tar.lz` files, but it still works for ruby's purposes.

2024-09-02 00:03 UTC, satmandu commented
Also, I expanded essential deps because installs were failing...

2024-09-02 00:05 UTC, Zopolis4 commented
> Also, I expanded essential deps because installs were failing...

In what situations were they failing? If I can test this PR and it works in that case, then we should be pretty good.

2024-09-09 03:20 UTC, Zopolis4 commented
any update on this? I'd like to get this PR in before it joins the pile of "out of sight out of mind" pull requests that have been waiting on reviews for months

and i've got some cleanup changes after this, including dealing with the warning constant message on crew startup, so i'd like to get those in as well

2024-09-09 11:12 UTC, satmandu commented
Will look at this again after I finish this massive python cleanup/update I'm on final approach for...

2025-01-10 12:47 UTC, Zopolis4 commented
Re: `generate_compatible`-- I don't see anything in that code that does anything other than check essential deps and package compatibility-- what exactly was your usecase?

I'll check out that other bug soon, swapped to a new laptop and distro and so am still setting up my development environment.

2025-02-07 04:47 UTC, uberhacker commented on tests/commands/remove.rb
> +        system "yes | crew install -d #{@package_with_essential_file}", %i[out err] => File::NULL
We can use `-f` now instead of `yes | ...`.

2025-02-07 05:57 UTC, Zopolis4 commented on tests/commands/remove.rb
> +        system "yes | crew install -d #{@package_with_essential_file}", %i[out err] => File::NULL
Fixed, thanks.

2025-02-07 06:23 UTC, uberhacker commented on lib/const.rb
> +CREW_ESSENTIAL_PACKAGES ||= %W[gcc_lib #{LIBC_VERSION.to_f > 2.34 ? "glibc_lib#{LIBC_VERSION.delete('.')}" : "glibc_build#{LIBC_VERSION.delete('.')}"} gmp ruby zlib zstd]
Bump crew version?

2025-02-07 06:27 UTC, Zopolis4 commented on lib/const.rb
> +CREW_ESSENTIAL_PACKAGES ||= %W[gcc_lib #{LIBC_VERSION.to_f > 2.34 ? "glibc_lib#{LIBC_VERSION.delete('.')}" : "glibc_build#{LIBC_VERSION.delete('.')}"} gmp ruby zlib zstd]
Fixed.

2025-02-07 06:36 UTC, uberhacker submitted a review, later dismissed

2025-02-07 07:01 UTC, Zopolis4 commented
Unit tests appear to be hanging-- I'll look into this when I get back.

2025-02-07 13:53 UTC, satmandu commented
It looks like removing packages previously deemed essential, such as `gcc_lib,` is breaking the container unit tests that check to ensure that trying to remove essential packages doesn't break things.

2025-02-07 23:59 UTC, Zopolis4 commented on tests/commands/remove.rb
> +        system "yes | crew install -d #{@package_with_essential_file}", %i[out err] => File::NULL
This causes hangs, so I've reverted it.

2025-02-08 00:00 UTC, Zopolis4 commented
FIxed-- the issue was just about using `yes | ...` instead of `crew -f` in the unit tests.

> It looks like removing packages previously deemed essential, such as `gcc_lib,` is breaking the container unit tests that check to ensure that trying to remove essential packages doesn't break things.

`gcc_lib` is still listed as an essential package and cannot be removed.

2025-02-08 00:14 UTC, satmandu approved these changes

2025-02-08 00:17 UTC, merged