Adwaita_icon_theme 40.1.1 => 42.0
chromebrew/chromebrew pull request #7154
Opened 2022-06-19 02:36 UTC by uberhacker

Fixes #7152.

2022-06-19 11:18 UTC, satmandu requested changes
Just needs the gnome flag added.

2022-06-19 11:18 UTC, satmandu commented on packages/adwaita_icon_theme.rb
> +
Also needs the `gnome` flag.

2022-06-19 15:48 UTC, uberhacker commented on packages/adwaita_icon_theme.rb
> +
Done.

2022-06-19 16:14 UTC, satmandu approved these changes

2022-06-23 18:56 UTC, supechicken approved these changes

2022-06-23 18:56 UTC, merged