Fix no_lto detection in meson and cmake buildsystems
chromebrew/chromebrew pull request #8486
Opened 2023-07-19 10:21 UTC by Zopolis4

Discovered this while working on some other stuff.

As an aside, setting `-DCMAKE_SHARED_LINKER_FLAGS` to `-fno_lto` breaks builds as `ar` interprets it as an argument. Not sure if this actually occurs after this fix though, or whether it was just in my specific environment, and so on. Just noting it here.

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/Zopolis4/chromebrew.git CREW_TESTING_BRANCH=flixesto CREW_TESTING=1 crew update
```

2023-07-19 12:00 UTC, satmandu commented on lib/buildsystems/cmake.rb
> +    @crew_cmake_options = @no_lto ? CREW_CMAKE_FNO_LTO_OPTIONS : CREW_CMAKE_OPTIONS
How does this handle detection of `no_lto` which would be set in a package?

2023-07-19 20:21 UTC, satmandu commented
@supechicken Can you help with this? `no_lto` is defaulting to `true` in `buildsystems/cmake` for some reason...

2023-07-19 20:38 UTC, satmandu commented
This doesn't work:
```ruby
require 'package'

class CMake < Package
  def self.cmake_options(options = '')
    return (@cmake_options = options if options)
  end

  def self.check?(bool = true)
    return (@check = bool)
  end

  def self.build
    puts "Additional cmake_options being used: #{@cmake_options.nil? || @cmake_options.empty? ? '<no cmake_options>' : @cmake_options}".orange
    if @pkg.no_lto?
      @no_lto = true
    else
      @no_lto = false
    end
    puts "no_lto is #{no_lto}, @no_lto is #{@no_lto}"
    @crew_cmake_options = @no_lto ? CREW_CMAKE_FNO_LTO_OPTIONS : CREW_CMAKE_OPTIONS
    @mold_linker_prefix_cmd = CREW_LINKER == 'mold' ? 'mold -run ' : ''
    system "#{@mold_linker_prefix_cmd}cmake -B builddir -G Ninja #{@crew_cmake_options} #{@cmake_options}"
    system "#{CREW_NINJA} -C builddir"
  end

  def self.install
    system "DESTDIR=#{CREW_DEST_DIR} #{CREW_NINJA} -C builddir install"
  end

  if @check
    def self.check
      system "#{CREW_NINJA} -C builddir test"
    end
  end
end
```

2023-07-19 22:43 UTC, satmandu commented
For the record, this PR does fix the symptom but not the underlying cause, which is causing `no_lto` to be detected as `true` when it is actually `false`...

2023-07-23 14:10 UTC, supechicken commented
> @supechicken Can you help with this? `no_lto` is defaulting to `true` in `buildsystems/cmake` for some reason...

The reason that the current setup does not work is because `no_lto` is used:
```ruby
@crew_cmake_options = no_lto ? CREW_CMAKE_FNO_LTO_OPTIONS : CREW_CMAKE_OPTIONS
```

(`no_lto` is used to **set** the flag to `true`, we should use `no_lto?` (notice the `?`) or `@no_lto` to **read** the flag)

That also explains why this PR fixes it :)

2023-07-23 14:21 UTC, satmandu commented
@supechicken where is `@no_lto` being set though?

2023-07-23 14:23 UTC, satmandu commented
I tried using this but it doesn't appear to set it correctly.

```ruby
if @pkg.no_lto?
   @no_lto = true
else
   @no_lto = false
end
```

2023-07-23 14:47 UTC, supechicken commented
> @supechicken where is `@no_lto` being set though?

In `package.rb` (under the `no_lto` method):

https://github.com/chromebrew/chromebrew/blob/e970f2a51dc721b83893cd96eb5446adf31a31eb/lib/package.rb#L147-L159


> I tried using this but it doesn't appear to set it correctly.
> 
> ```ruby
> if @pkg.no_lto?
>    @no_lto = true
> else
>    @no_lto = false
> end
> ```

It is because you called `no_lto` in the next line:
```ruby
puts "no_lto is #{no_lto}, @no_lto is #{@no_lto}"
```
This will set `no_lto` to `true` (you should use `no_lto?` here)

2023-07-24 07:36 UTC, Zopolis4 commented
So... is this PR the correct solution? A bit of that went over my head, I'll admit, but I'm happy to change this PR if I should do it another way.

2023-07-24 08:58 UTC, supechicken commented
> So... is this PR the correct solution? A bit of that went over my head, I'll admit, but I'm happy to change this PR if I should do it another way.

Yes, it is the correct way to deal with it (at least for me 😀)

2023-07-24 13:11 UTC, satmandu requested changes
Using `no_lto?` instead of `no_lto` should fix things...
We don't set `@no_lto` with the value of `no_lto` so I don't see how _that_ would work.

2023-07-24 13:11 UTC, satmandu commented on lib/buildsystems/cmake.rb
> +    @crew_cmake_options = @no_lto ? CREW_CMAKE_FNO_LTO_OPTIONS : CREW_CMAKE_OPTIONS
This needs to be 
```ruby
@crew_cmake_options = no_lto? ? CREW_CMAKE_FNO_LTO_OPTIONS : CREW_CMAKE_OPTIONS
```

2023-07-24 13:11 UTC, satmandu commented on lib/buildsystems/meson.rb
> +    @crew_meson_options = @no_lto ? CREW_MESON_FNO_LTO_OPTIONS : CREW_MESON_OPTIONS
This needs to be 
```ruby
@crew_meson_options = no_lto? ? CREW_MESON_FNO_LTO_OPTIONS : CREW_MESON_OPTIONS
```

2023-07-24 18:52 UTC, satmandu commented on lib/buildsystems/cmake.rb
> +    @crew_cmake_options = @no_lto ? CREW_CMAKE_FNO_LTO_OPTIONS : CREW_CMAKE_OPTIONS
Looks like I am wrong here!

2023-07-24 18:52 UTC, satmandu commented on lib/buildsystems/meson.rb
> +    @crew_meson_options = @no_lto ? CREW_MESON_FNO_LTO_OPTIONS : CREW_MESON_OPTIONS
I was wrong!

2023-07-24 18:52 UTC, satmandu approved these changes

2023-07-24 18:54 UTC, merged

2023-07-24 18:54 UTC, satmandu commented
Just putting `instance_variables` into a package file shows that `@no_lto` exists when `no_lto` is added to the package.