Add ots and love packages
chromebrew/chromebrew pull request #9349
Opened 2024-02-16 22:52 UTC by Zopolis4

Thought I'd work on clearing up the issue backlog-- easiest place to start is simple package requests.
Doing it in small groups so that no progress gets held up for too long, so just two packages for now.

- Adding [ots](https://github.com/khaledhosny/ots)
  - Resolves #2642
- Adding [love](https://github.com/love2d/love)
  - Resolves #3236
 
### Run the following to get this pull request's changes locally for testing.
```
CREW_REPO=https://github.com/Zopolis4/chromebrew.git CREW_BRANCH=lissue0 crew update
```

2024-02-16 23:06 UTC, uberhacker requested changes
Add new packages to `tools/packages.yaml`?

2024-02-16 23:16 UTC, uberhacker commented on tools/packages.yaml
> +url: https://github.com/khaledhosny/ots
This url should point to the releases or tags.  It indicates where updates can be downloaded.

2024-02-17 00:33 UTC, satmandu approved these changes

2024-02-17 00:38 UTC, uberhacker approved these changes

2024-02-17 00:38 UTC, merged