Add libversion package
chromebrew/chromebrew pull request #9983
Opened 2024-06-16 23:35 UTC by Zopolis4

Fixes #9941.

### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/Zopolis4/chromebrew.git CREW_BRANCH=watershed crew update
```

2024-06-16 23:41 UTC, uberhacker requested changes
Add to `core.rb` since it is a dependency of `tools/version.rb`?

2024-06-16 23:51 UTC, uberhacker commented on packages/core.rb
> +  depends_on 'libversion'
Bump core version?

2024-06-17 01:55 UTC, satmandu approved these changes

2024-06-17 01:56 UTC, satmandu approved these changes

2024-06-17 01:56 UTC, merged